services:
  db:
    image: mysql:8.0.34
    platform: linux/amd64
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: password
      TZ: "Asia/Tokyo"
    volumes:
      - ./db-data:/var/lib/mysql

  web:
    tty: true
    stdin_open: true
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
      - chromium
    environment:
      CHROMIUM_REMOTE_URL: http://chromium:4444/wd/hub

  chromium:
    image: seleniarm/standalone-chromium
    shm_size: 256m
    ports:
      - "4444:4444"

volumes:
  db-data:
